# Spring boot 2.6 이후 swagger 적용을 위한 ant_path_matcher 값 변경 설정
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
# profile 설정
spring:
  profiles:
    active: local
---
### mybatis 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(ouS6KgvjWYsJgipioKgSKr6l18ygue6YQfG9FUQCC7iMvhVXue1scGmXFKsJHVud)
    username: ENC(BfdfpbO0etaXYvt+o/1qIw==)
    password: ENC(VgBhQiHr9I112njdmGwpB4ulIKpShRXH)

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
---
### jwt token 설정
jwt:
  token:
    secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  access-token-validity-time: 3600
  refresh-token-validity-time: 36000
---
### redis connection 설정
spring:
   redis:
    host: localhost
    port: 6379
---
image:
  default-path: classpath:image
  upload-path: classpath:upload
#  upload-path: app/muna/upload
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(aORpLuEiZvUKSXwP2rOhqULGYxppjXgo)
    password: ENC(hURxLAJE6bnfq5bWCo0yh6XQDpo3e7Dtt+omwBKKALw=) # 4
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부
          #          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)
password:
  reset: classpath:templates/reset-password.html